name: Build DuckDB Postgres Extension (MinGW)

on:
  workflow_dispatch:

jobs:
  build-mingw:
    name: MinGW Build
    runs-on: windows-2022

    steps:
    - name: Checkout duckdb-postgres
      uses: actions/checkout@v4
      with:
        submodules: true  # pulls duckdb/ submodule too

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja

    - name: Build extension
      shell: msys2 {0}
      run: |
        git submodule update --init --recursive
        make

    - name: Test extension in duckdb shell
      shell: msys2 {0}
      run: |
        ./build/release/duckdb -unsigned ".mode table" ".load postgres"
