name: MinGW Build - duckdb-postgres

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build-mingw:
    runs-on: windows-2019
    name: Build with MinGW (MSYS2)

    steps:
      - name: Install MSYS2 and MinGW toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make mingw-w64-x86_64-toolchain

      - name: Clone duckdb-postgres repo
        shell: msys2 {0}
        run: |
          git clone https://github.com/Yousuf28/duckdb-postgres.git
          cd duckdb-postgres
          git submodule init
          git pull --recurse-submodules

      - name: Build with make
        shell: msys2 {0}
        run: |
          cd duckdb-postgres
          make

      - name: Run duckdb with unsigned extension
        shell: msys2 {0}
        run: |
          cd duckdb-postgres
          ./build/release/duckdb -unsigned
